### ISSUE TITLE
Copyheart?

### ISSUE THREAD

**Issue by pombredanne** [CottageLabs/esprit#12]
Hi: I am the maintainer of https://github.com/nexB/scancode-toolkit  a tool that detects licenses...
I never knew of the https://github.com/CottageLabs/esprit/blob/master/setup.py#L14 Copyheart license.... but you also have an Apache license text at your root.

As an act mercy for me and my vain attempts to properly detect licenses, would you care to clarify this?

**Comment by richard-jones** [comment]
Ah, the copyheart shouldn't be there - a copy and paste bug from an older library.  It's a fun concept though: http://copyheart.org/

I'll remove the copyheart from the setup.py in a moment.

**Comment by pombredanne** [comment]
No problem, there is pending PR to add it to scancode https://github.com/nexB/scancode-toolkit/pull/862 ;)
